# Generated by Django 3.0.2 on 2020-01-23 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('task_assign_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default='Not completed', max_length=50)),
            ],
        ),
    ]
